/** Generated by itemis CREATE code generator. */

#ifndef STATECHART_H_
#define STATECHART_H_

#ifdef __cplusplus
extern "C" { 
#endif

/*!
* Forward declaration for the Statechart state machine.
*/
typedef struct Statechart Statechart;

/*!
* Forward declaration of the data structure for the StatechartIfaceLight interface scope.
*/
typedef struct StatechartIfaceLight StatechartIfaceLight;

/*!
* Forward declaration of the data structure for the StatechartIfaceBut interface scope.
*/
typedef struct StatechartIfaceBut StatechartIfaceBut;

/*!
* Forward declaration of the data structure for the StatechartInternal interface scope.
*/
typedef struct StatechartInternal StatechartInternal;

#ifdef __cplusplus
}
#endif

#include "../src/sc_types.h"
#include <string.h>

#ifdef __cplusplus
extern "C" { 
#endif 

/*! \file
Header of the state machine 'Statechart'.
*/

#ifndef STATECHART_EVENTQUEUE_BUFFERSIZE
#define STATECHART_EVENTQUEUE_BUFFERSIZE 20
#endif
#ifndef STATECHART_IN_EVENTQUEUE_BUFFERSIZE
#define STATECHART_IN_EVENTQUEUE_BUFFERSIZE STATECHART_EVENTQUEUE_BUFFERSIZE
#endif
#ifndef SC_INVALID_EVENT_VALUE
#define SC_INVALID_EVENT_VALUE 0
#endif
/*! Define number of states in the state enum */
#define STATECHART_STATE_COUNT 5

/*! Define dimension of the state configuration vector for orthogonal states. */
#define STATECHART_MAX_ORTHOGONAL_STATES 1

/*! Define indices of states in the StateConfVector */
#define SCVI_STATECHART_A_BROWSE 0
#define SCVI_STATECHART_A_PRODUCTEXPELED 0
#define SCVI_STATECHART_A_INSERT 0
#define SCVI_STATECHART_A_ERROR 0
#define SCVI_STATECHART_A_CHANGEEXPELED 0


/* 
 * Enum of event names in the statechart.
 */
typedef enum  {
	Statechart_invalid_event = SC_INVALID_EVENT_VALUE,
	Statechart_but_B1,
	Statechart_but_B2,
	Statechart_but_B3,
	Statechart_but_B4
} StatechartEventID;

/*
 * Struct that represents a single event.
 */
typedef struct {
	StatechartEventID name;
} statechart_event;

/*
 * Queue that holds the raised events.
 */
typedef struct statechart_eventqueue_s {
	statechart_event *events;
	sc_integer capacity;
	sc_integer pop_index;
	sc_integer push_index;
	sc_integer size;
} statechart_eventqueue;

/*! Enumeration of all states */ 
typedef enum
{
	Statechart_last_state,
	Statechart_a_Browse,
	Statechart_a_ProductExpeled,
	Statechart_a_Insert,
	Statechart_a_Error,
	Statechart_a_ChangeExpeled
} StatechartStates;


/*! Type declaration of the data structure for the StatechartIfaceLight interface scope. */
struct StatechartIfaceLight
{
	sc_boolean L1;
	sc_boolean L2;
	sc_boolean L3;
	sc_boolean L4;
};



/*! Type declaration of the data structure for the StatechartIfaceBut interface scope. */
struct StatechartIfaceBut
{
	sc_boolean B1_raised;
	sc_boolean B2_raised;
	sc_boolean B3_raised;
	sc_boolean B4_raised;
};





/*! Type declaration of the data structure for the StatechartInternal interface scope. */
struct StatechartInternal
{
	sc_integer Balance;
	sc_integer Choice;
};






/*! 
 * Type declaration of the data structure for the Statechart state machine.
 * This data structure has to be allocated by the client code. 
 */
struct Statechart
{
	StatechartStates stateConfVector[STATECHART_MAX_ORTHOGONAL_STATES];
	StatechartIfaceLight ifaceLight;
	StatechartIfaceBut ifaceBut;
	StatechartInternal internal;
	sc_boolean isExecuting;
	statechart_eventqueue in_event_queue;
	statechart_event in_buffer[STATECHART_IN_EVENTQUEUE_BUFFERSIZE];
};



/*! Initializes the Statechart state machine data structures. Must be called before first usage.*/
extern void statechart_init(Statechart* handle);


/*! Activates the state machine. */
extern void statechart_enter(Statechart* handle);

/*! Deactivates the state machine. */
extern void statechart_exit(Statechart* handle);

/*! 
Can be used by the client code to trigger a run to completion step without raising an event.
*/
extern void statechart_trigger_without_event(Statechart* handle);



/*! Gets the value of the variable 'L1' that is defined in the interface scope 'light'. */ 
extern sc_boolean statechart_light_get_l1(const Statechart* handle);
/*! Sets the value of the variable 'L1' that is defined in the interface scope 'light'. */ 
extern void statechart_light_set_l1(Statechart* handle, sc_boolean value);
/*! Gets the value of the variable 'L2' that is defined in the interface scope 'light'. */ 
extern sc_boolean statechart_light_get_l2(const Statechart* handle);
/*! Sets the value of the variable 'L2' that is defined in the interface scope 'light'. */ 
extern void statechart_light_set_l2(Statechart* handle, sc_boolean value);
/*! Gets the value of the variable 'L3' that is defined in the interface scope 'light'. */ 
extern sc_boolean statechart_light_get_l3(const Statechart* handle);
/*! Sets the value of the variable 'L3' that is defined in the interface scope 'light'. */ 
extern void statechart_light_set_l3(Statechart* handle, sc_boolean value);
/*! Gets the value of the variable 'L4' that is defined in the interface scope 'light'. */ 
extern sc_boolean statechart_light_get_l4(const Statechart* handle);
/*! Sets the value of the variable 'L4' that is defined in the interface scope 'light'. */ 
extern void statechart_light_set_l4(Statechart* handle, sc_boolean value);
/*! Raises the in event 'B1' that is defined in the interface scope 'but'. */ 
extern void statechart_but_raise_b1(Statechart* handle);
/*! Raises the in event 'B2' that is defined in the interface scope 'but'. */ 
extern void statechart_but_raise_b2(Statechart* handle);
/*! Raises the in event 'B3' that is defined in the interface scope 'but'. */ 
extern void statechart_but_raise_b3(Statechart* handle);
/*! Raises the in event 'B4' that is defined in the interface scope 'but'. */ 
extern void statechart_but_raise_b4(Statechart* handle);

/*!
 * Checks whether the state machine is active (until 2.4.1 this method was used for states).
 * A state machine is active if it was entered. It is inactive if it has not been entered at all or if it has been exited.
 */
extern sc_boolean statechart_is_active(const Statechart* handle);

/*!
 * Checks if all active states are final. 
 * If there are no active states then the state machine is considered being inactive. In this case this method returns false.
 */
extern sc_boolean statechart_is_final(const Statechart* handle);

/*! Checks if the specified state is active (until 2.4.1 the used method for states was called isActive()). */
extern sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state);


#ifdef __cplusplus
}
#endif 

#endif /* STATECHART_H_ */
